CREATE TABLE [SPTG] (
  [IDX] LONG,
  [BL] LONG,
  [TAG] DATETIME,
  [ZEIT] TEXT(255),
  [HOME] TEXT(255),
  [GAST] TEXT(255),
  [TORE1] LONG,
  [TORE2] LONG,
  CONSTRAINT [PK_SPTG] PRIMARY KEY ([IDX]
);